#!/bin/sh

if [ ! -f JLex/Main.class ]; then
	javac JLex/Main.java
fi

java JLex.Main $1.lex && javac $1.lex.java && java $1

php5 -r "echo \"Word count: \" . str_word_count(file_get_contents(\"php://stdin\")) . \"\n\";" <$1.lex

